blocks:
  - name: Step1
    step:
      integration: 5c28f08d-9f3d-42bc-88bd-04b974ce99c8
      restapiintegration:
        authType: oauth-client-cred
        body: ""
        bodyType: jsonBody
        fileFormKey: ""
        fileName: ""
        formData: []
        headers:
          - key: Authorization
            value: Bearer f0slP0eHfo9Hhh_S3jOKTyENWaYGEzss
            valueOptions: []
        httpMethod: GET
        jsonBody: ""
        openApiAction: genericHttpRequest
        openApiSpecRef: ""
        params: []
        responseType: auto
        urlBase: ""
        urlPath: QfS4s-zco58HTHnPJB-uM2rDFqEI6Cjrs
metadata:
  description: ""
  folder: ""
  id: 021e507b-6337-4d31-a33d-7be5cfa2c0b0
  name: Add_product
  organization: a8fabcf7-bc27-49cd-a718-f16cc6e9e86a
  tags: {}
  timestamps:
    updated: 2024-01-09T13:47:40.818Z
  version: ""
trigger:
  application:
    id: 687b112f-3112-4e28-9457-08ddc9113149
